import { supabase } from '../lib/supabase';
import type { MenuItem, TableOrder } from '../types';

// Add this bill's total to today's running total in daily_sales (upsert).
async function adjustDailySale(saleDate: string, amountDelta: number, orderCountDelta: number) {
  const { data: existing } = await supabase.from('daily_sales').select('*').eq('sale_date', saleDate).maybeSingle();
  if (existing) {
    await supabase
      .from('daily_sales')
      .update({
        total_amount: Math.max(0, parseFloat(existing.total_amount) + amountDelta),
        order_count: Math.max(0, existing.order_count + orderCountDelta),
      })
      .eq('sale_date', saleDate);
  } else if (amountDelta > 0) {
    await supabase.from('daily_sales').insert([{ sale_date: saleDate, total_amount: amountDelta, order_count: 1 }]);
  }
}

// Saves a printed bill: one row in `orders` (status 'active', counted
// immediately — no separate confirmation step), one row per line item in
// `order_items`, and updates the permanent date-wise `daily_sales` ledger.
// Returns the new order's id so the caller can embed it in the UPI QR note
// before printing, which is what lets BharatPe payments be matched back to
// this exact bill later.
export async function saveOrderToDB(tableNumber: number, tableOrder: TableOrder, menuItems: MenuItem[]) {
  const entries = Object.entries(tableOrder).filter(([, qty]) => qty > 0);
  const total = entries.reduce((sum, [itemId, qty]) => {
    const item = menuItems.find((m) => m.id === Number(itemId));
    return sum + (item ? item.price * qty : 0);
  }, 0);

  const { data: order, error: orderErr } = await supabase
    .from('orders')
    .insert([{ table_number: tableNumber, total, status: 'active', payment_method: 'upi_pending' }])
    .select()
    .single();
  if (orderErr) throw orderErr;

  const orderItems = entries
    .map(([itemId, qty]) => {
      const item = menuItems.find((m) => m.id === Number(itemId));
      if (!item) return null;
      return {
        order_id: order.id,
        menu_item_id: item.id,
        item_name: item.name,
        item_price: item.price,
        quantity: qty,
        subtotal: item.price * qty,
      };
    })
    .filter((x): x is NonNullable<typeof x> => x !== null);

  const { error: itemsErr } = await supabase.from('order_items').insert(orderItems);
  if (itemsErr) throw itemsErr;

  await adjustDailySale(order.created_at.split('T')[0], total, 1);

  return { orderId: order.id as number, total };
}

// Voids a bill that was generated by mistake (wrong table, duplicate,
// kitchen error, test print). Pulls it back out of the day's total instead
// of leaving staff to manually confirm every correct bill instead.
export async function missBill(orderId: number) {
  const { data: order, error: fetchErr } = await supabase
    .from('orders')
    .select('*')
    .eq('id', orderId)
    .single();
  if (fetchErr) throw fetchErr;
  if (order.status === 'missed') return; // already voided, nothing to do

  const { error: updateErr } = await supabase
    .from('orders')
    .update({ status: 'missed' })
    .eq('id', orderId);
  if (updateErr) throw updateErr;

  const saleDate = order.created_at.split('T')[0];
  await adjustDailySale(saleDate, -parseFloat(String(order.total)), -1);
}

// One-tap manual tag for a bill paid in cash. Skips the BharatPe matching
// entirely for this order since there's no UPI transaction to reconcile.
export async function markCash(orderId: number) {
  const { error } = await supabase.from('orders').update({ payment_method: 'cash' }).eq('id', orderId);
  if (error) throw error;
}
